'use client'

// The emoji list shared by the icon picker and the editor's ":" menu
// (generated by scripts/generate-emoji.ts), loaded the first time it's needed.

/** [emoji, name, search words, five skin-tone variants]. */
export type EmojiEntry = [emoji: string, label: string, words: string, skins?: string[]]
export type EmojiData = { groups: { name: string; emoji: EmojiEntry[] }[] }

let data: Promise<EmojiData> | null = null
export const loadEmoji = () => (data ??= import('@/components/notebooks/emojiData.json').then((m) => m.default as EmojiData))

const TONE_KEY = 'personal-os:emoji-tone'

/** 0 = default yellow, 1–5 = light to dark (the picker's ✋ setting). */
export function readTone(): number {
  try {
    return Number(JSON.parse(localStorage.getItem(TONE_KEY) ?? '0')) || 0
  } catch {
    return 0
  }
}

export function writeTone(tone: number) {
  try {
    localStorage.setItem(TONE_KEY, JSON.stringify(tone))
  } catch {
    // Storage off: the tone just isn't remembered.
  }
}

export const withTone = (e: EmojiEntry, tone: number) => (tone && e[3] ? e[3][tone - 1] : e[0])

/** Every word of the query must appear in the emoji's Chinese or English words. */
export function searchEmoji(all: EmojiEntry[], query: string): EmojiEntry[] {
  const words = query.trim().toLowerCase().split(/\s+/).filter(Boolean)
  if (!words.length) return all
  return all.filter((e) => words.every((w) => e[2].includes(w)))
}
