'use client'

// The Phosphor component behind each page icon name in lib/noteIcons.ts.

import {
  Airplane,
  Alarm,
  Anchor,
  Archive,
  Atom,
  Bank,
  Barbell,
  Bed,
  Bicycle,
  Binoculars,
  BookBookmark,
  BookOpen,
  BookmarkSimple,
  Books,
  Brain,
  Briefcase,
  Bug,
  Buildings,
  Calculator,
  CalendarBlank,
  CalendarCheck,
  Camera,
  Car,
  Carrot,
  Cat,
  Certificate,
  ChalkboardTeacher,
  ChartBar,
  ChartLine,
  ChartPie,
  ChatCircle,
  Chats,
  CheckCircle,
  CheckSquare,
  ClipboardText,
  Clock,
  Cloud,
  CloudSun,
  Code,
  Coffee,
  Coins,
  Compass,
  CookingPot,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Desktop,
  DeviceMobile,
  Diamond,
  Dog,
  Drop,
  Envelope,
  Exam,
  Eye,
  Feather,
  FileText,
  FilmSlate,
  Fire,
  Flag,
  Flask,
  FlowArrow,
  Flower,
  Folder,
  ForkKnife,
  GameController,
  Gavel,
  Gear,
  Gift,
  Globe,
  GlobeHemisphereEast,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  Heartbeat,
  HighlighterCircle,
  Hourglass,
  House,
  HouseLine,
  Image,
  Info,
  Kanban,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Lightning,
  Link,
  ListChecks,
  Lock,
  MagicWand,
  MapPin,
  MapTrifold,
  Medal,
  Megaphone,
  Microphone,
  Money,
  Moon,
  Mountains,
  MusicNotes,
  Newspaper,
  NotePencil,
  Notebook,
  PaintBrush,
  Palette,
  Paperclip,
  PawPrint,
  Pen,
  PenNib,
  PencilSimple,
  PersonSimpleRun,
  Phone,
  PiggyBank,
  Pill,
  Plant,
  PresentationChart,
  PushPin,
  PuzzlePiece,
  Question,
  Receipt,
  Robot,
  Rocket,
  Scales,
  ShieldCheck,
  ShoppingCart,
  Smiley,
  Sparkle,
  Star,
  Storefront,
  Student,
  Suitcase,
  Sun,
  Table,
  Tag,
  Target,
  Tent,
  TerminalWindow,
  Timer,
  Train,
  Translate,
  Tree,
  TreeStructure,
  Trophy,
  Umbrella,
  User,
  Users,
  VideoCamera,
  Wallet,
  Warning,
  Wrench,
  type Icon,
} from '@phosphor-icons/react'
import type { NoteIconName } from '@/lib/noteIcons'

export const NOTE_ICON_COMPONENTS: Record<NoteIconName, Icon> = {
  'file-text': FileText,
  'note-pencil': NotePencil,
  notebook: Notebook,
  'book-open': BookOpen,
  books: Books,
  'book-bookmark': BookBookmark,
  'bookmark-simple': BookmarkSimple,
  'graduation-cap': GraduationCap,
  student: Student,
  exam: Exam,
  certificate: Certificate,
  translate: Translate,
  'chalkboard-teacher': ChalkboardTeacher,
  lightbulb: Lightbulb,
  brain: Brain,
  'pencil-simple': PencilSimple,
  'pen-nib': PenNib,
  pen: Pen,
  feather: Feather,
  'highlighter-circle': HighlighterCircle,
  paperclip: Paperclip,
  'push-pin': PushPin,
  tag: Tag,
  archive: Archive,
  folder: Folder,
  'clipboard-text': ClipboardText,
  'list-checks': ListChecks,
  'check-square': CheckSquare,
  'calendar-blank': CalendarBlank,
  'calendar-check': CalendarCheck,
  clock: Clock,
  timer: Timer,
  alarm: Alarm,
  hourglass: Hourglass,
  briefcase: Briefcase,
  buildings: Buildings,
  'house-line': HouseLine,
  storefront: Storefront,
  bank: Bank,
  scales: Scales,
  gavel: Gavel,
  calculator: Calculator,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'presentation-chart': PresentationChart,
  table: Table,
  database: Database,
  kanban: Kanban,
  'tree-structure': TreeStructure,
  'flow-arrow': FlowArrow,
  code: Code,
  'terminal-window': TerminalWindow,
  laptop: Laptop,
  desktop: Desktop,
  'device-mobile': DeviceMobile,
  cpu: Cpu,
  cloud: Cloud,
  globe: Globe,
  link: Link,
  gear: Gear,
  wrench: Wrench,
  hammer: Hammer,
  flask: Flask,
  atom: Atom,
  robot: Robot,
  bug: Bug,
  key: Key,
  lock: Lock,
  'shield-check': ShieldCheck,
  'chat-circle': ChatCircle,
  chats: Chats,
  envelope: Envelope,
  phone: Phone,
  user: User,
  users: Users,
  microphone: Microphone,
  headphones: Headphones,
  'music-notes': MusicNotes,
  camera: Camera,
  image: Image,
  'film-slate': FilmSlate,
  'video-camera': VideoCamera,
  newspaper: Newspaper,
  megaphone: Megaphone,
  house: House,
  coffee: Coffee,
  'fork-knife': ForkKnife,
  'cooking-pot': CookingPot,
  carrot: Carrot,
  barbell: Barbell,
  'person-simple-run': PersonSimpleRun,
  bicycle: Bicycle,
  heartbeat: Heartbeat,
  pill: Pill,
  drop: Drop,
  bed: Bed,
  'game-controller': GameController,
  palette: Palette,
  'paint-brush': PaintBrush,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  wallet: Wallet,
  money: Money,
  coins: Coins,
  'piggy-bank': PiggyBank,
  receipt: Receipt,
  'credit-card': CreditCard,
  umbrella: Umbrella,
  sun: Sun,
  moon: Moon,
  'cloud-sun': CloudSun,
  plant: Plant,
  leaf: Leaf,
  tree: Tree,
  flower: Flower,
  mountains: Mountains,
  tent: Tent,
  'paw-print': PawPrint,
  dog: Dog,
  cat: Cat,
  airplane: Airplane,
  train: Train,
  car: Car,
  suitcase: Suitcase,
  anchor: Anchor,
  'globe-hemisphere-east': GlobeHemisphereEast,
  'map-trifold': MapTrifold,
  'map-pin': MapPin,
  compass: Compass,
  binoculars: Binoculars,
  star: Star,
  heart: Heart,
  'hand-heart': HandHeart,
  smiley: Smiley,
  sparkle: Sparkle,
  'magic-wand': MagicWand,
  fire: Fire,
  lightning: Lightning,
  rocket: Rocket,
  target: Target,
  flag: Flag,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  diamond: Diamond,
  'puzzle-piece': PuzzlePiece,
  'check-circle': CheckCircle,
  eye: Eye,
  question: Question,
  info: Info,
  warning: Warning,
}
