/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'daily-logs': DailyLog;
    tasks: Task;
    habits: Habit;
    'weekly-reviews': WeeklyReview;
    'monthly-notes': MonthlyNote;
    journals: Journal;
    'toefl-scores': ToeflScore;
    ideas: Idea;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'daily-logs': DailyLogsSelect<false> | DailyLogsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    habits: HabitsSelect<false> | HabitsSelect<true>;
    'weekly-reviews': WeeklyReviewsSelect<false> | WeeklyReviewsSelect<true>;
    'monthly-notes': MonthlyNotesSelect<false> | MonthlyNotesSelect<true>;
    journals: JournalsSelect<false> | JournalsSelect<true>;
    'toefl-scores': ToeflScoresSelect<false> | ToeflScoresSelect<true>;
    ideas: IdeasSelect<false> | IdeasSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-logs".
 */
export interface DailyLog {
  id: number;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  date: string;
  habitsDone?: (number | Habit)[] | null;
  toeflMinutes?: number | null;
  toeflSkills?: ('speaking' | 'writing' | 'reading' | 'listening' | 'vocab')[] | null;
  themeMinutes?: number | null;
  energy?: number | null;
  morningPlan?: string | null;
  noonPlan?: string | null;
  eveningPlan?: string | null;
  /**
   * Notion 式編輯器的區塊資料（在前台編輯）
   */
  note?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habits".
 */
export interface Habit {
  id: number;
  name: string;
  icon: 'headphones' | 'barbell' | 'drop' | 'book' | 'run' | 'moon' | 'leaf' | 'pill' | 'pencil' | 'check';
  weeklyTarget: number;
  position?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  title: string;
  kind: 'important' | 'weekly';
  status: 'todo' | 'done' | 'migrated';
  position?: number | null;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  day?: string | null;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  weekStart?: string | null;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  dueDate?: string | null;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  startDate?: string | null;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  endDate?: string | null;
  /**
   * Notion 式編輯器的區塊資料（在前台編輯）
   */
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  migratedFrom?: (number | null) | Task;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-reviews".
 */
export interface WeeklyReview {
  id: number;
  /**
   * 該週的週一，YYYY-MM-DD
   */
  weekStart: string;
  /**
   * Notion 式編輯器的區塊資料（在前台編輯）
   */
  review?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  theme?: (number | null) | Idea;
  themeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideas".
 */
export interface Idea {
  id: number;
  title: string;
  why?: string | null;
  /**
   * 對托福、工作或長期目標的幫助（0–3）
   */
  scoreGoal?: number | null;
  /**
   * 有沒有時間壓力（0–3）
   */
  scoreUrgency?: number | null;
  /**
   * 現在有多想學（0–3）
   */
  scorePassion?: number | null;
  /**
   * 自動計算
   */
  total?: number | null;
  status: 'inbox' | 'selected' | 'done' | 'dropped';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-notes".
 */
export interface MonthlyNote {
  id: number;
  /**
   * YYYY-MM
   */
  month: string;
  /**
   * Notion 式編輯器的區塊資料（在前台編輯）
   */
  review?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journals".
 */
export interface Journal {
  id: number;
  year: number;
  title: string;
  subtitle?: string | null;
  coverColor: 'navy' | 'forest' | 'burgundy' | 'charcoal';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "toefl-scores".
 */
export interface ToeflScore {
  id: number;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  date: string;
  type: 'mini' | 'section' | 'full' | 'official';
  source?: ('ets' | 'third-party' | 'ai') | null;
  reading?: number | null;
  listening?: number | null;
  speaking?: number | null;
  writing?: number | null;
  /**
   * 四科都有級分時自動計算
   */
  overall?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'daily-logs';
        value: number | DailyLog;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'habits';
        value: number | Habit;
      } | null)
    | ({
        relationTo: 'weekly-reviews';
        value: number | WeeklyReview;
      } | null)
    | ({
        relationTo: 'monthly-notes';
        value: number | MonthlyNote;
      } | null)
    | ({
        relationTo: 'journals';
        value: number | Journal;
      } | null)
    | ({
        relationTo: 'toefl-scores';
        value: number | ToeflScore;
      } | null)
    | ({
        relationTo: 'ideas';
        value: number | Idea;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-logs_select".
 */
export interface DailyLogsSelect<T extends boolean = true> {
  date?: T;
  habitsDone?: T;
  toeflMinutes?: T;
  toeflSkills?: T;
  themeMinutes?: T;
  energy?: T;
  morningPlan?: T;
  noonPlan?: T;
  eveningPlan?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  status?: T;
  position?: T;
  day?: T;
  weekStart?: T;
  dueDate?: T;
  startDate?: T;
  endDate?: T;
  body?: T;
  migratedFrom?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habits_select".
 */
export interface HabitsSelect<T extends boolean = true> {
  name?: T;
  icon?: T;
  weeklyTarget?: T;
  position?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "weekly-reviews_select".
 */
export interface WeeklyReviewsSelect<T extends boolean = true> {
  weekStart?: T;
  review?: T;
  theme?: T;
  themeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-notes_select".
 */
export interface MonthlyNotesSelect<T extends boolean = true> {
  month?: T;
  review?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journals_select".
 */
export interface JournalsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  subtitle?: T;
  coverColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "toefl-scores_select".
 */
export interface ToeflScoresSelect<T extends boolean = true> {
  date?: T;
  type?: T;
  source?: T;
  reading?: T;
  listening?: T;
  speaking?: T;
  writing?: T;
  overall?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ideas_select".
 */
export interface IdeasSelect<T extends boolean = true> {
  title?: T;
  why?: T;
  scoreGoal?: T;
  scoreUrgency?: T;
  scorePassion?: T;
  total?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  planStart: string;
  /**
   * YYYY-MM-DD（台灣時間）
   */
  examDate?: string | null;
  baselineBand?: number | null;
  targetBand?: number | null;
  checkpoints?:
    | {
        week: number;
        target: number;
        id?: string | null;
      }[]
    | null;
  weeklyTargets?: {
    toeflHours?: number | null;
  };
  weekPlan: {
    mon: 'speaking' | 'writing' | 'reading' | 'listening' | 'vocab' | 'practice' | 'rest';
    tue: 'speaking' | 'writing' | 'reading' | 'listening' | 'vocab' | 'practice' | 'rest';
    wed: 'speaking' | 'writing' | 'reading' | 'listening' | 'vocab' | 'practice' | 'rest';
    thu: 'speaking' | 'writing' | 'reading' | 'listening' | 'vocab' | 'practice' | 'rest';
    fri: 'speaking' | 'writing' | 'reading' | 'listening' | 'vocab' | 'practice' | 'rest';
    sat: 'speaking' | 'writing' | 'reading' | 'listening' | 'vocab' | 'practice' | 'rest';
    sun: 'speaking' | 'writing' | 'reading' | 'listening' | 'vocab' | 'practice' | 'rest';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  planStart?: T;
  examDate?: T;
  baselineBand?: T;
  targetBand?: T;
  checkpoints?:
    | T
    | {
        week?: T;
        target?: T;
        id?: T;
      };
  weeklyTargets?:
    | T
    | {
        toeflHours?: T;
      };
  weekPlan?:
    | T
    | {
        mon?: T;
        tue?: T;
        wed?: T;
        thu?: T;
        fri?: T;
        sat?: T;
        sun?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}